version: "3.8"

services:
  web:
    environment:
      - PYTHONPATH=/app
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/myportfolio 
    depends_on: 
      - db
      
  db:
    image: postgres
    restart: always
    env_file: 
      - .env 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped 
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - web

volumes:
  postgres_data:
  nginx_secrets:
