name: Docker

on:
  # Trigger workflow on push/pull request for master branch
  push: 
    branches:
      - master
  pull_request:
    branches: 
      - master
  
jobs:
  build-docker:
    name: Build Docker container
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository 
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Build Docker container
        uses: docker/build-push-action@v2
